### ISSUE TITLE
Restore Classification copy

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1806]
Restore the Classification section/panel links which disappeared recently.
- `Copy from parent`
<img width="406" alt="Screenshot 2024-01-13 at 6 24 20 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/15b64631-5eee-4da3-8a5e-6d0f1cb717a6">

 This link displayed at least as recently as deploy-2024-01-09-22-26 234e230c09b433e398d41dfd97561f8a6e0636d2

### Tasks

- [x] Add test exposing bug
- [x] Get test green
- [x] Rubocop test method
- [x] PR
- [ ] Merge & deploy if CI is green

**Comment by JoeCohen** [comment]
In deploy-2024-01-09-22-26 234e230c09b433e398d41dfd97561f8a6e0636d2 `app/views/controllers/names/show/_classification.html.erb` was
```ruby
<%
approved_name = @name.approved_name
parents = approved_name.all_parents
%>

<%= if approved_name.classification.present? && parents.any?
  tag.div(class: "mb-2") do
    ([approved_name] + parents).reverse.each do |n|
      concat(tag.p do
        concat("#{rank_as_string(n.rank)}: ")
        concat(tag.i(link_with_query(n.text_name.t, n.show_link_args)))
        if n == approved_name && approved_name != @name
          concat([
            safe_br, safe_nbsp, safe_nbsp, " (= ", tag.i(@name.text_name.t), ")"
          ].safe_join)
        end
      end)
    end
  end
end %>

<%= if @first_child
  type = @name.at_or_below_genus? && !@name.at_or_below_species? ?
    :rank_species : :show_subtaxa_obss
  tag.p do
    link_to(:show_object.t(type: type),
            add_query_param(names_path, @children_query))
  end
end %>

<%= if @name.below_genus? &&
        @name.accepted_genus.try(&:classification).to_s.strip !=
        @name.classification.to_s.strip
  tag.p do
    put_button(
      name: :show_name_refresh_classification.t,
      path: add_query_param(refresh_name_classification_path(@name.id))
    )
  end
end %>

<%= if @name.rank == "Genus" && @first_child && @name.classification.present?
  tag.p do
    put_button(
      name: :show_name_propagate_classification.t,
      path: add_query_param(propagate_name_classification_path(@name.id))
    )
  end
end %>

<% if !@name.below_genus? && @name.classification.blank?
  tag.p do
    link_with_query(:show_name_inherit_classification.t,
                    inherit_name_classification_form_path(@name.id))
  end
end %>
```

**Comment by JoeCohen** [comment]
It's a trivial typo (a missing `=`) in `app/views/controllers/names/show/_classification.html.erb`: 
Should be 
`<%= if !@name.below_genus? && @name.classification.blank?`
instead of
`<% if !@name.below_genus? && @name.classification.blank?`
