### ISSUE TITLE
iNat import

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1955]
This task embodies the simplest acceptable functionality for NEMF 2024

### Tasks
- [ ] Add MO project to Obs if it meets project criteria && user is a member
- [ ] Perhaps change redirect from Observations to Observations by current user.
- [ ] Rubocop

### Completed
- [x] iNat observations/photos with restrictive licenses (e.g. nonderivs, Options: Don't import; require MO user consent).
- [x] Remove import all option from form
- [x] Fix conflicts with main.
- [x] #2341 
- [x] Different flash if obs ##s missing
- [x] #2219 
- [x] #2246 - [x] Import single iNat Observation (in foreground, unauthenticated)
- [x] Isolate call to MO API instead of conditioning images on non-test environment.
- [x] Change API Key to something temporary that I can delete after fixing environment variables
- [x] Add production MO API Key for webmaster
- [x] ?? Slime molds: Better solution than `iconic_taxon_name: "Protozoa"`? probably too complicated:  ("Slime molds" are polyphyletic).

**Comment by JoeCohen** [comment]
iNat API documents:
- https://api.inaturalist.org/v1/docs/
- https://www.inaturalist.org/pages/api+recommended+practices

**Comment by JoeCohen** [comment]
To play with API requests:
- Go to  [iNaturalist API](https://api.inaturalist.org/v1/docs/) 
- Scroll down to the list of objects
- Click on an object (e.g. `Observations`)
- Click an Operation (e.g. `GET Observations` aka `Observation Search`)

Here is a A very simple API request for a single iNat Observation (202555552). It returns tons of data. 
https://api.inaturalist.org/v1/observations?id=202555552

**Comment by JoeCohen** [comment]
- [Authentication](https://www.inaturalist.org/pages/api+reference#auth) (How to get authentication to retrieve iNat private data.)

**Comment by JoeCohen** [comment]
I should probably with importing a single iNat Observation, deal with authentication later.

**Comment by JoeCohen** [comment]
`test/fixtures/inat/one_obs_public.json` 
(in https://github.com/MushroomObserver/mushroom-observer/tree/jdc-1955-inat-import) 
is what this returns
```ruby
HTTParty.get("https://api.inaturalist.org/v1/observations?id=202555552&order=desc&order_by=created_at&only_id=false")
```
It's a search for a single iNat obs, 202555552, without authenticating, so it just returns public data.

 I 'd like to stub that request,bu I'm having issues with understanding/converting raw string to JSON. 
So to move forward I will stub something more abstract.

**Comment by JoeCohen** [comment]
Some "fixture" files, in test/fixtures/inat/:
- `one_obs_public.txt` What iNat API returns for an observation search for obs iNat 202555552 
- `one_obs_public.json` The above as json. Handy because it's more readable than the above, but not really used in tests.

**Comment by JoeCohen** [comment]
Photos
They're in aws.
pseudocode:
```ruby
obs[:observation_photos].each do |photo|
  aws_id = photo[:photo_id]
  import this: https://inaturalist-open-data.s3.amazonaws.com/photos/<aws_id>/original.jpeg`
end
```

to get image to local tmp file (per Copilot)
```ruby
require 'open-uri'

url = 'http://example.com/image.png' # Replace with the actual image URL
local_file_path = Rails.root.join('tmp', 'image.png') # Specify the local file path

# Download the image and save it locally
IO.copy_stream(open(url), local_file_path)

# Now `local_file_path` contains the downloaded image
```
Tempfile Class: The Tempfile class in Ruby provides a convenient way to manage temporary files. When you create a Tempfile object, it automatically generates a unique filename in the OS’s temp directory. You can perform standard file operations on it, such as reading, writing, and changing permissions. Here’s how you can use it:
```ruby
require 'tempfile'

file = Tempfile.new('foo')
file_path = file.path # A unique filename in the OS's temp directory
file.write('hello world')
file.rewind
content = file.read
file.close
file.unlink # Deletes the temp file
```

**Comment by JoeCohen** [comment]
#### How do I copy an image from an external website to a (temp) file on the server?

Nathan Wilson <nathan@collectivesource.com>	Sun, Apr 21, 2024 at 5:04 AM
...
At least leveraging the code in the API makes sense to me.  Not sure it's worth creating a service that just translates between the APIs, but it would be cool and might get us to at least improve the online documentation around our API.  I heard at last year's NAMA foray that ChatGPT is better at creating code using the iNat API than the MO API.  I think Alan has looked at that and might have some examples.

> On Sun, Apr 21, 2024 at 12:19 AM Jason Hollinger <[pellaea@gmail.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=pellaea@gmail.com)> wrote:
Yes, check out around line 58 of app/classes/api2/core/uploads.rb for one possible solution.
It might be altogether a dumb idea to literally just use the API to accomplish your whole task.

**Comment by mo-nathan** [comment]
> #### How do I copy an image from an external website to a (temp) file on the server?
> Nathan Wilson [nathan@collectivesource.com](mailto:nathan@collectivesource.com) Sun, Apr 21, 2024 at 5:04 AM ... At least leveraging the code in the API makes sense to me. Not sure it's worth creating a service that just translates between the APIs, but it would be cool and might get us to at least improve the online documentation around our API. I heard at last year's NAMA foray that ChatGPT is better at creating code using the iNat API than the MO API. I think Alan has looked at that and might have some examples.
> 
> > On Sun, Apr 21, 2024 at 12:19 AM Jason Hollinger <[pellaea@gmail.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=pellaea@gmail.com)> wrote:
> > Yes, check out around line 58 of app/classes/api2/core/uploads.rb for one possible solution.
> > It might be altogether a dumb idea to literally just use the API to accomplish your whole task.

I'd either use system to call one of the standard command line tools for this (curl or wget) or I'd explore a Ruby library like [Open::URI](http://rubydoc.info/stdlib/open-uri/1.9.2/frames). See https://stackoverflow.com/questions/6768238/download-an-image-from-a-url

**Comment by nimmolo** [comment]
Good to know, i was wondering the same thing. We use File class methods all over MO.

In the stack overflow answer:

I'd go after the file using Ruby's Open::URI:

require "open-uri"

File.open('pie.png', 'wb') do |fo|
  fo.write open("http://chart.googleapis.com/chart?#{failures_url}").read 
end

I wondered, how is he using Open::URI here, though? 
The answer seems to be that any URL that begins with `protocol://` <protocol://%60> is parsed by URI if File.open is called.

**Comment by JoeCohen** [comment]
From `README_API.md`
>* POST <https://mushroomobserver.org/api2/observations?api_key=xxx&name=Agaricus&location=Pasadena,+California,+USA&date=2016-08-06&notes=growing+in+lawn>
>
> The response will include the id of the new record.
>
> Attach the image as POST data or URL.  See `script/test_api` for an example of how to attach an image in the POST data.

There is no `script/test_api`.
Maybe `test/controllers/api2_controller_test.rb#test_post_maximal_image`?
```ruby
  def test_post_maximal_image
    setup_image_dirs
    rolf.update(keep_filenames: "keep_and_show")
    rolf.reload
    file = Rails.root.join("test/images/Coprinus_comatus.jpg").to_s
    proj = rolf.projects_member.first
    obs = rolf.observations.first
    File.stub(:rename, false) do
      post_and_send_file(:images, file, "image/jpeg",
                         api_key: api_keys(:rolfs_api_key).key,
                         vote: "3",
                         date: "20120626",
                         notes: " Here are some notes. ",
                         copyright_holder: "My Friend",
                         license: licenses(:ccnc30).id.to_s,
                         original_name: "Coprinus_comatus.jpg",
                         projects: proj.id,
                         observations: obs.id)
    end
    ...
  end

  def post_and_send_file(action, file, content_type, params)
    body = Rack::Test::UploadedFile.new(file, "image/jpeg").read
    md5sum = file_checksum(file)
    post_and_send(action, body, content_type, md5sum, params)
  end

  def post_and_send(action, body, content_type, md5sum, params)
    @request.env["CONTENT_TYPE"] = content_type
    @request.env["CONTENT_MD5"] = md5sum
    post(action, params: params, body: body)
  end
```
Better: `test/models/api2_test.rb#test_posting_image_via_url`
```ruby
  def test_posting_image_via_url
    setup_image_dirs
    url = "https://mushroomobserver.org/images/thumb/459340.jpg"
    stub_request(:any, url).
      to_return(Rails.root.join("test/images/test_image.curl").read)
    params = {
      method: :post,
      action: :image,
      api_key: @api_key.key,
      upload_url: url
    }
    File.stub(:rename, false) do
      api = API2.execute(params)
      assert_no_errors(api, "Errors while posting image")
      img = Image.last
      assert_obj_arrays_equal([img], api.results)
      actual = File.read(img.local_file_name(:full_size))
      expect = Rails.root.join("test/images/test_image.jpg").read
      assert_equal(expect, actual, "Uploaded image differs from original!")
    end
  end
```

**Comment by JoeCohen** [comment]
Following is returns by API help request `http://localhost:3000//api2/images?help=1`
```json
{
"version": 2,
"run_date": "2024-05-04T11:40:53.075Z",
"errors": [
{
"code": "API2::HelpMessage",
"details": "Usage: confidence: confidence range (limit=-3..3); content_type: enum list (limit=bmp|gif|jpg|png|raw|tiff); copyright_holder_has: string (search within copyright holder); created_at: time range; date: date range (when photo taken); has_notes: boolean; has_observation: boolean (limit=true, is attached to an observation?); has_votes: boolean; id: integer list; include_subtaxa: boolean; include_synonyms: boolean; license: license; location: location list; name: name list; notes_has: string (search within notes); observation: observation list; ok_for_export: boolean; project: project list; quality: quality range (limit=1..4); size: enum (limit=huge|large|medium|small|thumbnail, width or height at least 160 for thumbnail, 320 for small, 640 for medium, 960 for large, 1280 for huge); species_list: species_list list; updated_at: time range; user: user list (who uploaded the photo)",
"fatal": "true"
}
],
"run_time": 0.017291
}
```

**Comment by JoeCohen** [comment]
### Is iNat Obs in _Fungi_?

Taxa page for _Fungi_: https://www.inaturalist.org/taxa/47170-Fungi_
So `[:taxon][:ancestor_ids] `must include 47170
alternative: `[:taxon][:iconic_taxon_name] == "Fungi"`

**Comment by JoeCohen** [comment]
### iNat Projects Issue. 
I cannot reliably get an iNat observation's Projects via the new API.
Apparently I can get it from the old API. https://www.inaturalist.org/pages/api+reference#get-observations

**Comment by JoeCohen** [comment]
for `contains_box`, I need to have a (separate?) scope which generalizes this (from #2183)

```ruby
  scope :contains, # Use named parameters (lat:, lng:), any order
        lambda { |**args|
          args => {lat:, lng:}
          where(
            Location[:south].lteq(lat).and(Location[:north].gteq(lat)).
            and(
              Location[:west].lteq(lng).and(Location[:east].gteq(lng)).or(
                Location[:west].gteq(lng).and(Location[:east].lteq(lng))
              )
            )
          )
        }
```

**Comment by nimmolo** [comment]
How about something like this, that takes advantage of named arg assignment:
```ruby
  scope :contains, # Use named parameters (lat:, lng:, or north:, south:, east:, west:), any order
        lambda { |**args|
          if args.lat.present? && args.lng.present?
            args => {lat:, lng:}
            north = south = lat
            east = west = lng
          else if args.north.present?
            args => {north:, south:, east:, west:}
          end
          where(
            Location[:south].lteq(south).and(Location[:north].gteq(north)).
            and(
              Location[:west].lteq(west).and(Location[:east].gteq(east)).or(
                Location[:west].gteq(west).and(Location[:east].lteq(east))
              )
            )
          )
        }
```
Not sure about all that, but something like that.

**Comment by JoeCohen** [comment]
@nimmolo Yes. That looks right.  Needs some tests, especially for e/w.
What's the best procedure for adding this:
- stand-alone PR vs. main?
- include it in #1955?
- include it in #2183?
- stand-alone PR vs #2183?
- other?

**Comment by nimmolo** [comment]
I'd say do it as a standalone PR vs main. We have plenty of scopes as yet unused, and one more won't hurt — plus of course I'll use the lat/lng part in my next PR.

**Comment by JoeCohen** [comment]
Thanks. Will do.

**Comment by JoeCohen** [comment]
iNat [API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices)

**Comment by JoeCohen** [comment]
mirror adds string like this to Notes:
```ruby
Mirrored on iNaturalist as <a href="https://www.inaturalist.org/observations/194293541">observation 194293541</a> on December 18, 2023.
```
