### ISSUE TITLE
Revive MyCoPortal exports

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1956]
Export MO Observations to MyCoPortal. (Last export was 22 July 2019. See [here](https://www.mycoportal.org/portal/collections/misc/collprofiles.php?collid=36.))

### Tasks

- [x] Re-review available MyCoPortal Symbiota fields
- [x] #2919
- [x] #2921
- [x] #2929
- [x] Contact Scott Bates with list of questions
- [x] #2942
- [x] Try to fix Notes issues. Ex: Textile link https://www.mycoportal.org/portal/api/v2/occurrence/8187446
>For iNat, we are now just uploading one image url per record via the catalog number. This encourages users to link out to the original record in the source (viz. MO) database (hence the importance of that verbatimAttributes link-out). 
We can do this in batch via another table that is just catalogNumber|imageURL. If you could provide that table with one image as well, that would be great.
- [ ] #2927

**Comment by JoeCohen** [comment]
What's needed to revive updates to MCP. (An excerpt, some formatting changed) from an email chain "db numbers for herbaria" in webmaster email.)
Check the chain for later important information.

-----

Scott Bates <scott.thomas.bates@gmail.com
Mon, Dec 9, 2024, 9:08 AM
	
to Joseph, Mycoportal, me, Nathan
Hello Joe:

Thanks again for the productive meeting on Friday.

As mentioned in order to update and aggregate observational records from Mushroom Observer for the MyCoPortal we would need output (e.g., a csv file) with the following fields:

*for the following record - https://www.mycoportal.org/portal/collections/editor/occurrenceeditor.php?occid=7962944

- **dbpk**: e.g., 514 (I believe I misspoke, I think it is actually the dbpk number that serves as a reference for updating - e.g., finding an existing record that needs to be overridden - and not the catalog number - here we simply used the MO number without zero padding)
- **catalogNumber**: e.g., MUOB 514 (as we discussed the prefix 'MUOB' + space + non-zero padded MO number format would have to be generated)
- **BasisOfRecord**: HumanObservation (this would be the same for all MO records)
- **sciName**: e.g., Amanita muscaria subsp. flavivolvata (we do not include authors as those will be populated by our taxonomic thesaurus)
- **observer**: e.g., Nathan Wilson (a given name is preferred; however, user names can serve as a substitute)
- **number**: e.g., MUOB 514 (this is actually the collector number; however, we mirror the MO number for simplicity)
- **date**: e.g., 2003-12-06 (only this format Y-M-D w/ zero padding is accepted)
- **verbatimDate**: 2003-12-6 (this is a text field and can be anything)
- **country**: e.g., United States (as we discussed, parsing these locality data are likely the most challenging aspect here)
- **stateProvince**: e.g., California
- **county**: e.g., Mendocino
- **locality**: e.g., Jackson Demonstration State Forest
- **decimalLatitude**: 39.3645
- **decimalLongitude**: e.g., -123.627
- **description**: e.g., '<a href='http://mushroomobserver.org/514' target='_blank' style='color: blue;'>Original observation #514 (Mushroom Observer)</a>' (as we discussed, these links back to MO in this format would have to be generated)
notes: e.g., Found during a foray sponsored by the Fungus Federation of Santa Cruz.

Again, we do not archive/store images and have always preferred to link out to the source image (we do, however, generate thumbnails). I believe Phil Anders (the Illinois Natural History Survey Bioinformatician CCd here) would be able to help with the image linkages if we had a table file (e.g., csv) with the catalogNumber and image URLs.

Also, here is documentation for the MyCoPortal API:
- https://www.mycoportal.org/portal/api/v2/documentation

You might be interested in the following, for example:
- https://www.mycoportal.org/portal/api/v2/occurrence/search?catalogNumber=MUOB%20514&limit=100&offset=0
- https://www.mycoportal.org/portal/api/v2/occurrence/7962944

Remember that the 'occid' serves as an internal index of sorts for each record in the portal.

As we discussed, once we create an upload profile w/ mapping, any future update would be fairly trivial.

I am more than happy to provide further instructions regarding the uploading process or can walk you through it.

Many thanks again, a MO update would be fantastic as those records would be contributing directly to our fungal conservation project.

Don't hesitate to ask if you have further questions.

Cheers,

Scott
------------------------------------------
Scott T. Bates, PhD
Nils K. Nelson Endowed Professor
Dept. of Biological Sciences
Purdue University Northwest
(219) 785-5484
stbates@purdue.edu
http://stbates.org
------------------------------------------

**Comment by JoeCohen** [comment]
More documentation.
[MyCoPortal](https://www.mycoportal.org/portal/)
[Symbiota](https://symbiota.org/) MCP is a Symbiota Portal
 - [Symbiota docs](https://biokic.github.io/symbiota-docs/)
 - [Symbiota Data Fields](https://biokic.github.io/symbiota-docs/editor/edit/fields/#standard-fields)

Fields displayed when a MO record is displayed in MCP:
`Symbiota ID | Collection | Catalog Number | Family | Scientific Name | Collector | Number | Date | Country | State/Province | County | Locality | Decimal Lat. | Decimal Long. | Habitat | Substrate | Elevation`
- Number = Collector's # ||= Catalog Number
- Substrate = blank in most cases, but we've populated some. Seems to rely on MO Notes `Substrate` field if present.

**Comment by JoeCohen** [comment]
Link to MCP display of search in MUOB for _Sarcopshaera coronaria_
https://www.mycoportal.org/portal/collections/listtabledisplay.php?db=36&taxa=Sarcosphaera+coronaria&usethes=1&taxontype=2

Clicking on one record in that display, I see: 
<img width="819" alt="Image" src="https://github.com/user-attachments/assets/61a1fda4-23b6-48ec-8b6c-de956cd56ef3" />

**Comment by JoeCohen** [comment]
Questions for us.
In tsv export, then uploaded to Google doc:
- source of lat/lng.??  Perhaps obs lat/lng || centrum of `observation.location`
- RecordNumber looks like collection number || `observation.id`

**Comment by JoeCohen** [comment]
Questions for us.
In tsv export, then uploaded to Google doc:
- source of lat/lng.??  Perhaps obs lat/lng || centrum of `observation.location`
- RecordNumber looks like collection number || `observation.id`

**Comment by JoeCohen** [comment]
Convert difference in lng degrees to meters:
js formula
```js
function measure(lat1, lon1, lat2, lon2){  // generally used geo measurement function
    var R = 6378.137; // Radius of earth in KM
    var dLat = lat2 * Math.PI / 180 - lat1 * Math.PI / 180;
    var dLon = lon2 * Math.PI / 180 - lon1 * Math.PI / 180;
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon/2) * Math.sin(dLon/2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R * c;
    return d * 1000; // meters
}
```
