### ISSUE TITLE
Location#merge incomplete

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2084]
`Location#merge` fails to update `herbarium.location_id`.
That causes a broken reference for any Herbarium which used the merged Location.

### Tasks
- [x] Write a test exposing the bug.
- [x] Fix the bug.
- [x] Double check to make sure to make sure that merge isn't neglecting another association.
- [x] Suggestion: include the `id` of the non-surviving Location in the admin note which is added to Location.notes

**Comment by JoeCohen** [comment]
It's also fails to update Projects, leaving a broken reference there.
Perhaps need some meta-programming/reflection in tests to assure that:
- There's fixture for each class that could be affected by a location merger
- The fixture's `location` changes.

**Comment by pellaea** [comment]
Thanks, Joe.  Interesting that check_for_broken_references didn't find
that.  Every association should look like "belongs to" *somewhere*.
Many-to-many has to have a glue table, each of whose records will "belong
to" both of the original tables, for example.  And so on.  So why wasn't
check_for_broken_references picking up that association and therefore
noticing the broken reference between project and the missing location?

**Comment by JoeCohen** [comment]
It didn't find it because there's not yet any such broken reference.
There's no Project whose Location was merged after the Project was created.
(There are only 7 Project's with a non-nil location.)

**Comment by pellaea** [comment]
Ah!  Okay, thanks.  Good catch, then.  How novel, catching a bug *before*
it causes a problem! :)
