### ISSUE TITLE
Update CC Licenses

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2156]
Update CC licenses after merger of #2154 

### TODO
- [x] Deploy #2154
- [x] Remove display of Default #2165
- [x] Use new Licenses UI to add [new Licenses and 4.0 versions of existing licenses](https://creativecommons.org/licenses/).
- [x] Use new Licenses UI to deprecate older versions of 4.0 licenses.
- [x] Insure that all Licenses have `created_at` and `updated_at` present, directly modifying db via the back end. (Check https://github.com/MushroomObserver/mushroom-observer/blame/main/app/models/license.rb for best dates).
- [x] PR changing Images.license_id default and Users.license_id default to latest version of by-sa
- [x] Fix created_at display in show template.
