### ISSUE TITLE
iNat Location

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2218]
Covert iNat Location to MO Location when importing iNat observations
iNat observations have a location (lat/lng point) and positional accuracy (in meters).
Convert this to the MO Location that is the MBR (Minimum Bounding Rectangle) of  the iNat Location +/- `public_positional_accuracy`.

### Tasks
- [x] new Location scope  `contains` see https://github.com/MushroomObserver/mushroom-observer/issues/1955#issuecomment-2197751209
- [ ] calculate inat box = (iNat Location +/- `public_positional_accuracy)
- [ ] Consider -- if the MBR is too large -- creating a new MO Location

**Comment by JoeCohen** [comment]
Get list of locations containing lat/lng + public accuracy
Create a box. Maybe mappable box methods will help, as I need to add meters to lat, lng
  n = max (lat + public accuracy, 90), s = max (lat - public accuracy, 90), e/w get tricky because public accuracy can push box to other side of 180. Maybe first 
mbr_area = infinity
mbr = nil
each loc 
  loc area  = calculate are
  next unless loc_area < mbr_area

  mbr = loc
  mbr_area = loc_area
end

Perhaps I can partly piggy-back on app/classes/mappable/box.rb, app/classes/mappable/box_methods.rb

**Comment by JoeCohen** [comment]
> Andrew Nimmo
The BoxMethods class computes area, and the AutoComplete::ForLocationContaining class sorts by this method. You could use that as an example.

https://mushroomobserver.slack.com/archives/C040TH9FV/p1720559425916179

**Comment by nimmolo** [comment]
Suggestion - If the iNat obs contains only a point location, we probably do not need an MO location.
- Convert the lat/lng point to the obs lat/lng, and forget fudging the point to an MBR. Some iNat obs presumably have non-point Locations, and these are the ones we should be importing (according to this suggestion)
- Use the `contains` scope to match the iNat observation lat/lng to an existing MO Location, or create a new MO Location by polling Google, as the form does (shortly).

**Comment by nimmolo** [comment]
Interesting. 

Sounds like we should be taking the smallest encompassing iNat "Place" and getting the name and bounding box of that. (Any `geometry` column should also have the MBR available in the data list, it's part of the spec.) We could ignore the other geometry of the place. The place is the one that's likely to have a meaningful, searchable Name, and this name may even correspond to an MO Location. 

The most attractive option to me, since in my mind we are moving towards using `geometry` columns for Locations in the near future, would be to import the iNat Place geometry into MO without necessarily using it yet. 

If we move to the `geometry` data type for obs and locations, observations will no longer need an associated Location, only a lat/lng. The user can search for a Location like "Cochise Co., Arizona, USA" and the database query can pretty easily compute all observations lie within that geometry. That's a significant improvement over MO, where the obs must be _explicitly associated with_ Cochise Co., not one of the towns within it, to show up in such a search. This is how iNat is doing it, i would imagine.

I don't think we have a use for the "accuracy" stuff yet, although it would be good if we did. I still feel like an MBR produced from their accuracy radius is little better than fudging points, it doesn't really add to the accuracy or searchability.

**Comment by JoeCohen** [comment]
- `geometry` would be cool. But I'll file it for future reference. I don't want to delay iNat imports.
- For importing iNat observations, I start by importing the observation data. That data has a list of bare place_ids, no other info about the places. Looks like this: `"place_ids":[1,20,1976,9853,51894,59613,59649,59954 ...]`. So I'd have to make another query to get place details.
  - The place details include a single bounding box, which is a polygon. They do not include a minimum bounding **rectangle**.
  - The place details include a bbox_area, like this `"bbox_area": 0.0000192242584172317`. I assume this is the area of the bounding polygon, not the area of a bounding rectangle.  (The units appear to be thousands of square km's. I haven't checked the documentation.
- I think we do need the accuracy stuff because we need to fudge some points, because some of the observations we are importing have obscured or hidden lat/lng. And MO should make them publicly at least obscure as they were in iNat.
- Other. I just found out that iNat has both public and private lat/lng and positional_accuracy. More documentation [here](https://www.inaturalist.org/pages/help#geoprivacy). I don't know if we can get access to the private stuff.

**Comment by nimmolo** [comment]
There is a way to get an MBR from the Place polygon, even if that polygon is not a box (i.e. rectangle). There's both a db-native way, and mathematical-function way. 

(I'm still feeling like one of iNat's Places is likely the most relevant "Location" we'd want to save for our users, because it's likely to conform to the kind of string a user would enter, as a generally-recognized name of an area.)
