### ISSUE TITLE
bulk iNat import

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2224]
Import many Observations. For instance, users should have the option to import all their iNat Obss.
Possibly date/location limited imports

### Tasks
- [x] Allow multiple listed IDs
  - [x] Change form `iNat observation number` to `numbers` 
  - [x] Mention comma separated list
  - [x] Change work flow: get one page of results, Iterate over the results, repeat until out of pages
    - [x] Refactor params to always include: ids; sort by id, asc; allow optional additional params
    - [x] #2250
    - [x] Revise controller test stub
    - [x] Revise controller params
  - [x] Fix the stubs in the model tests. 
The stubs must return entire search results (which include the obs), rather than just the obs. 
Reason: controller has changed so that it does a search, which it will go per page; each page per result (obs)
    - [x] Revert one mock
    - [x] Fix the model stub to do a search, return a single result
  - [x] Import multiple IDs if user included multiple ids on form
- [x] iNat Username 
  - [x] Add it to form
  - [x] make it mandatory
  - [x] Add it to InatImport and to search string
- [x] Add option to import all a user's Obss 
  - [x] Modify form  
- [x] Redo order of params: mirror [iNat example/test page](https://api.inaturalist.org/v1/docs/#!/Observations/get_observations).  Ex:
`https://api.inaturalist.org/v1/observations?id=231104466&user_login=devin189&iconic_taxa=Fungi&id_above=0&per_page=200&order=asc&order_by=id&only_id=true`
  - [x] change order in call to RestClient
  - [x] change order in stubs
- [x] Manual test: add appropriate bpt, try importing all my Obss.

**Comment by JoeCohen** [comment]
iNat limits # of ids to 30 when using `https://api.inaturalist.org/v1/observations/10000,10001,...`

**Comment by JoeCohen** [comment]
This is Erroring in MO 
`RestClient::UnprocessableEntity in Observations::InatImportsController#authenticate`
`@inat = RestClient.get("#{API_BASE}#{operation}", headers)`
```
>> "#{API_BASE}#{operation}"
=> "https://api.inaturalist.org/v1/observations?id=&id_above=0&only_id=false&per_page=200&order=asc&order_by=id&user_login=dev189&iconic_taxa=Fungi,Protozoa"
>> headers
=> {"Authorization"=>"Bearer {\"access_token\":\"_VLnaihHahFntdN2nne_U2Clv7eJyJkpo8i-WutIdeg\",\"token_type\":\"Bearer\",\"scope\":\"write login\",\"created_at\":1722123661}"}
```
I've tried it in the console with the same result. Also tried it without a header. Tried it with and empty header `{ }`.
This is working on the[ iNat API test page](https://api.inaturalist.org/v1/docs/#!/Observations/get_observations):
`https://api.inaturalist.org/v1/observations?user_login=devin189&iconic_taxa=Fungi&id_above=0&per_page=200&order=asc&order_by=id&only_id=true`

**Comment by nimmolo** [comment]
Are you sure `headers` is encoded right? I spot two different hash notations, the `=>` and the `:`

**Comment by JoeCohen** [comment]
thanks!  that could be it. will check tomorrow
