### ISSUE TITLE
map iNat sequences to MO

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2226]
Map iNat Observation Fields with sequences to MO sequences. 
Issue: iNat lacks uniform treatment of isequences. The data can be in a  variety of user-created Observation Fields. It's a free-for-all. 

### Tasks
- [x] Map iNat [DNA-type Observation Fields](https://www.inaturalist.org/observation_fields?utf8=%E2%9C%93&q=dna&commit=Search)
- [x] Ensure that Sequences work on Sigrid Jakob observations.
- [x] Ensure that Sequences work on Danny Miller observations.
- [x] Check other observations in [2023 NEMF list](https://docs.google.com/spreadsheets/d/1ow0ekqbPs6jgIobPK3OIF6sT42cw6cCZDZyBK3sb9Hw/edit?gid=2100696196#gid=2100696196)

**Comment by JoeCohen** [comment]
Danny MIller iNat Observations with sequences. https://api.inaturalist.org/v1/observations?ofv_datatype=DNA&user_id=dannymi&order=desc&order_by=created_at&only_id=true

**Comment by JoeCohen** [comment]
Sigrid uses "DNA Barcode ITS" which is a DNA-type field, so we're good.
