### ISSUE TITLE
Include Proposed Names

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2227]
Include each unique iNat identification as a Proposed Name.
Issues: 
- what confidence? Maybe none, except Community id is "could be"
- Who owns Naming? User if originally his iNat Id, else webmaster
- Notes. Keep it simple to start. Just ignore these. Users can go to iNat to get details.

### Tasks
- [x] Add InatTaxon class, including tests
- [x] Controller test
- [x] ensure correct user owns Naming
- [x] ensure correct weight for Naming
- [x] ensure Community Vote correct
- [x] Manual test
- [x] Add test for Obs where User proposed the consensus
- [x] Combine the t mesenterica tests
