### ISSUE TITLE
Better test of iNat imports controller

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2228]
More robust test of InatImportsController

### Tasks
- [x] Test "fixture" with images
- [x] Improve coverage of iNatImportsController. (Ideally 100%)
- [x] Can I stub the call to the authorization_url to make it redirect to `#auth`?
- [x] ?? Stub calls to aws. 
Or otherwise test if multiple images are handled correctly per image, e.g., correct dates, uuid, license per image.

**Comment by JoeCohen** [comment]
Closing: Controller is covered 100%.
