### ISSUE TITLE
iNat import form

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2231]
Refine/expand the iNat import form 

### Tasks
- [x] Require user consent
- [x] `iNat id:` => `iNat observation numbers` 
- [x] Add text based on Pulk README
- [x] Add text based on Pulk app ui
- [x] Describe which iNat fields are mapped to MO fields
- [x] Describe which iNat fields are not mapped to MO fields
- [x] Describe other limits, such as Projects
- [x] Mention that iNat Obs will be modified with an MO Observation Field
- [x] Consider solicit suggestions about mapping other fields
