### ISSUE TITLE
iNat DNA detail Observation Fields

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2232]
Handle Observation Fields that are sequence details.
"Handle" == map to an MO Field; include in Sequence Notes;  include in initial comment with appropriate details and link; or ignore.

### Tasks
- [ ] Genbank Accession Number - map to Sequence, Deposit: archive, accession
- [ ] MycoMap BLAST Results, e.g., https://mycomap.com/genetics/blast-search/rhodocybe-84618879-r24412.  Some options:
  - (a) simply include in Initial Data, 
  - (b) include in Notes
  - (c) include in Sequence Notes
  - (d) add a MycoMap BLAST results field somewhere, probably in Sequences
- [ ] Reads in Consensus (RiC). Ex: Reads in Consensus. ex: 158
- [ ] Sequencing technology. Ex: Nanopore (ONT)
- [ ] Trace Files (Raw DNA Data): ex: https://mycomap.com/genetics/sequences/ont_sequences/g08-nemf23-087-inat184222420-1-r124070/

**Comment by mo-nathan** [comment]
I think adding fields to the Sequence is the right approach.  I'd like to reduce the giant set of notes on each observation.
