### ISSUE TITLE
Cleanup (misc.)

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2234]
A bunch of things I didn't have time to put in other issues

### Tasks
- [x] Consider new class InatSearch with attributes/methods like: `results`, `first_observation`, `pages` etc.
- [x] InatImports#new flash warning and redisplay import form if neither iNat ids or other params to select iNat obss. 
- [ ] InatImports#new remove flash warning and for multiple iNat ids. Huh?
- [ ] InatImports#new links to return to CreateObservation or ObservationIndex
- [ ] Prove that photos use individual photo license rather than Observation license_code. This is just a test to prevent regression; it already works that way. I probably need to use an existing mock obs, modify the photo license.
- [x] Can I filter Observation searches to exclude ones with `Mushroom Observer URL` observation field? 
- [x] Redefine `REDIRECT_URI` from local to webserver.
Login to iNat as jdc; goto https://www.inaturalist.org/oauth/applications/851
- [x] Custom User-Agent for iNat API requests? See iNat [API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices)
- [x] Should we respect taxon privacy? (Maybe we don't have a choice.)
- [x] Delete unused mock test files and update Readme
- [x] "Original: iNaturalist #24970904" => something analogous to Originally posted to Mushroom Observer on Nov. 10, 2021
- [x] ?? consider adding a ref to iNat provisional if creating a Name
- [x] How should MO pick the Location of an obscured iNat obs? Use MO's internal obscuring or iNat's `public_positional_accuracy`.
- [x] Add user_name `[user:][name:]` if present to initial comment
- [x] strip iNat Username coming from form
- [x] Shorten/clean up Info/Caveats on new Import form
