### ISSUE TITLE
Manually test authentication.

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2240]
### Tasks
- [ ] Confirm that importing confidential data fails in branch (**_new_**  iNat API, [Authorization Code Flow](https://www.inaturalist.org/pages/api+reference#get-observations)): 
Import one of my obscured iNat obss [215996396](https://inaturalist.org/observations/215996396). 
 ==> Actual lat/lng:  **44.4659, -121.6967**.

In results returned by the **_new_**  iNat API Observations have fields like this:
```ruby 
:positional_accuracy=>20,
:public_positional_accuracy=>20,
:location=>"31.8813,-109.244",
```
- [ ] Replicate what @nimmolo did in Postman: Use Postman to import this obs with **_old_** iNat API, [Authorization Code Flow](https://www.inaturalist.org/pages/api+reference#get-observations).
**_old_** iNat API has different fields. I think like this:
```ruby
"latitude": "41.2995543746",
"longitude": "-72.5571845909",
"positional_accuracy": 7798,
``` 
- [ ] Use Postman to import the obs with **_new_** API, [Authorization Code Flow](https://www.inaturalist.org/pages/api+reference#get-observations).
url: `https://api.inaturalist.org/v1/observations?id=215996396`
Cf [Authorization Code Flow](https://www.inaturalist.org/pages/api+reference#get-observations):
```ruby
token = JSON.parse(response)["access_token"]
headers = {"Authorization" => "Bearer #{token}"}
puts "GET /users/edit.json, headers: #{headers.inspect}"
puts RestClient.get("#{site}/users/edit.json", headers)
```
If that succeeds, then there's a problem with my code.

httparty "https://api.inaturalist.org/v1/observations?id=215996396&order=desc&order_by=created_at&only_id=false" -H Authorization:"Bearer {"access_token":"cbcvBMqA9k40UEfvX4CrBrtUVEv-tXy3vzrcB-OWfMU","token_type":"Bearer","scope":"write login","created_at":1721343212}"

**Comment by JoeCohen** [comment]
An obscured jdc observation: https://inaturalist.org/observations/215996396

**Comment by JoeCohen** [comment]
Argh. iNat Observations have both public and private: location (lat/lng) accuracy. 
The private information is not visible via an unauthenticated API request.
I'm not sure about authenticated requests.

**Comment by JoeCohen** [comment]
@nimmolo says:

New API, this works (corrected and updated!): (edited) 
[Slack](https://mushroomobserver.slack.com/archives/D011FQX2CLV/p1723581472377349)
 
# restclient CLI
```ruby
irb(main):001> oauth_token_request = RestClient::Request.execute(method: :post, url: "https://www.inaturalist.org/oauth/token", headers: { params: { client_id: {{app_id}}, client_secret: {{app_secret}}, grant_type: :password, username: {{username}}, password: {{password}} }, accept: :json })
=> <RestClient::Response 200 "{\"access_token...">
​
irb(main):002> require "JSON"
irb(main):003> token = JSON.parse(oauth_token_request)["access_token"]
irb(main):004> jwt = RestClient::Request.execute(method: :get, url: "https://www.inaturalist.org/users/api_token", headers: { authorization: "Bearer #{token}", accept: :json } ) 
=> <RestClient::Response 200 "{\"api_token...">
# the response is a stringified JSON hash, because we requested json in the 
# header with `accept: :json`
​
# just take the value of the "api_token"
irb(main):005> jwt_value = JSON.parse(jwt)["api_token"]
irb(main):006> observations_request = RestClient::Request.execute(method: :get, url: "http://api.inaturalist.org/v1/observations", headers: { params: { user_id: 6321993, ttl: "-1" }, accept: :json, authorization: "Bearer #{jwt_value}" })
=> <RestClient::Response 200 "{\"total_res...">
​
irb(main):007> response = JSON.parse(observations_request)
=> {"total_results"=>46,
​
irb(main):008> observations = response["results"]
=> [{"quality_grade"=>"research",
	
# For reference: this works via the old API, using the oauth token 
# (no need for the JWT)
irb(main):009> observations = RestClient::Request.execute(method: :get, url: "http://www.inaturalist.org/observations.json", headers: { params: { user_id: 6321993 }, accept: :json, authorization: "Bearer #{token}" })
```
