### ISSUE TITLE
Testing updates

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2242]
Miscellaneous testing related updates

### Tasks
- [x] In CI use `main` instead of `master` + fixed version. See https://github.com/coverallsapp/github-action/issues/201#issuecomment-2234228863
- [x] Update Rubocop
- [x] Update Rubocop version used by CodeClimate
- [x] Consider updating Rubocop todo

**Comment by JoeCohen** [comment]
We are already using the highest available rubocop channel used by Codeclimate.
That channel is 1-56-3. See https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
So we're using a higher Rubocop locally -- 1.65.0 -- than in CI.
