### ISSUE TITLE
Simplify InatObs

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2250]
Refactor InatObs to be just the obs, rather than a page with one obs

### Tasks
- [x] Revise recipe for creating a mock obs
- [x] Redo one mock obs
- [x] Refactor InatObs
- [x] Run a model test which includes that mock
- [x] redo the other mocks
- [x] fix lentinellus_ursinus mock
- [x] fix model test failures
- [x] check evernia mock -- it may now have a photo
- [x] controller test
- [x] fix the funky `@imported_inat_obs_data =
      JSON.parse(imported_inat_obs_data, symbolize_names: true)`
