### ISSUE TITLE
Change iNat Import Manager

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2284]
Change the User which owns special objects created during iNat imports (e.g., Namings not first proposed by the User who is doing the import; the iNat data comment)

NOTE: 2025-09-19. This has a little higher priority since emails started working better. The special user is starting to get emails about comments on the imported Obs an other stuff. 

### Tasks

- [ ] A better Name for that user
- [ ] Create email address at mushroomobserver.org
- [ ] Create the User in the live db
- [ ] Create profile of the User
- [ ] Update preferences, especially no email
- [ ] Create a test User in users.yml. Can I simply change the `webmaster` test user?
- [ ] Make all tests pass

**Comment by nimmolo** [comment]
Are these "users" going to stick around in the db?

I'm sure you've thought about it, but bringing in namings and ALSO phantom users, it sounds like a lot of junk data. 

Only having thought about it this minute admittedly, I'd lean towards attributing all the "objects coming from iNat imports that do not belong to the importing User" to a single all-purpose "other iNat User", unless you think these phantoms could eventually be "rehydrated" into real MO users, for example if the original object owner ALSO signs up with MO.

**Comment by JoeCohen** [comment]
@nimmolo Great questions.
1. There will only ever be one such user, so I'm not worried about proliferation of phantom users.
2. I don't regard the Namings are junk data. They are as useful for Observations imported from iNat as for any other MO Observation. 
NOTE: I think there should be at least one Naming per imported Observation. (Else the Observation has a Name without a Naming, which seems weird and might have unanticipated side-effects.)
The (initial) MO Observation.name corresponds to the iNat Community Taxon. iNat may not have an `identification` which corresponds to the Community Taxon. So I think I should associate an MO user with that. 
(Ex: iNat obs has 2 `identifications`: _Russula brevipes_ and  _R. cascadensis_. The iNat Community ID will be _Russula_, even though no iNat user has suggested that Name.) 
Also, for each iNat import I'm creating an initial Comment that summarizes the state of the iNat obs. I don't want that Comment to belong to the User who created the import (because I don't want that User to be able to modify that Comment.)
4. IMO it's too complicated to later change the object owner to an MO user.

**Comment by nimmolo** [comment]
Sounds good. # 1 seems to answer it, i didn't notice how the user was being used.

(I didn't mean to imply the Namings were junk data, but that the Naming users were potentially junk data, if there was a new mystery user created for each Naming.)

**Comment by JoeCohen** [comment]
@nimmolo I'm happy to consider different ways of doing this.

**Comment by nimmolo** [comment]
Well, when you say "there will only ever be one such user" do you mean that you'll create one all-purpose "iNat user" who will be the attributed user for all the Namings not attributed to the importing User? If that's how you're doing it, that seems ideal. 

It's creating a new fake user for each imported Naming [not proposed by the importing User] that would be my concern - potentially many thousands of fake Users for each power user whose data we import. 

We query the User table all the time, often with wasteful duplicate queries, and doubling the size of the User table would be my junk data scenario, and carry a performance penalty.

**Comment by JoeCohen** [comment]
i mean the former. one iser resposible for all the imports.

**Comment by JoeCohen** [comment]
Closing as obsolete. The manger has been completely eliminated. Each importing user gets their own API, and (going forward) all model objects created during an import belong to an individual MO user.
