### ISSUE TITLE
Use Stimulus to update JobTracker Status

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2319]
Improve Job Tracker by updating it with Stimulus, improving details.

### Tasks
- [x] Find and study some examples
- [x] Add js inat-import-job-controller
- [ ] update only **Status** display (start by updating just this part of the view)
  - [x] Modify app/views/controllers/inat_import_job_trackers/show.html.erb
  - [x] Add tests
  - [x] Fix redirect to authorization_url
  - [x] Change Callback URL on iNat for the [MushroomObserver Test app](https://www.inaturalist.org/oauth/applications/851)
  - [x] Refactor InatImports#show view per Nimmo suggestion
  - [x] Simplify `authorization_response`; remove unneeded ivars
  - [x] Remove the manually updated `Status`
  - [x] Rename partial, e.g. `updates`
  - [x] Manual test: particularly the manual buttons.
  - [x] RuboCop
  - [x] PR Ready for review
  - [x] Merge & Deploy
  - [ ] change Callback URL on iNat for the [MushroomObserverTest app](https://www.inaturalist.org/oauth/applications/857)
- [ ] Update other items with Stimulus/Turbo. (a separate PR)

**Comment by JoeCohen** [comment]
Stimulus examples
app/javascript/controllers/field-slip-job_controller.js
#2520
