### ISSUE TITLE
Simplify Proposed Names

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2386]
### Tasks
When adding a Proposed Name (corresponding to an iNat suggested id) 
- [x] Just one Proposed Name. See https://mushroomobserver.slack.com/archives/C040TH9FV/p1732480165238419
- [x] Proposed Name reason should be `Used References`
- [x] `Used References` notes should include iNat username and date. 
- [x] Naming user should be:
  - [x] If the iNat user who suggested the identification is an MO user, the Proposal should be by that MO User 
  - [x] else (including when Community ID was not an identification), the import manager (currently MO Webmaster)
  - [x] Analgous treatment for provisionals.
- [x] The Snapshot should include all suggested IDs, with iNat username, date
See [Slack suggestion by @AlanRockefeller ](https://mushroomobserver.slack.com/archives/C040TH9FV/p1732319550054449)
- [x] Manual test

**Comment by JoeCohen** [comment]
Won't be simple.
In order to add the reason, in `add_naming_with_vote` I have to:
- if the naming is a provisional, see who suggested that field. I don't know if I can get the date.
- else, 
  - find the first iNat identification with that name pseudo code [:identifications] where [:taxon][:name] == name
  - the user who suggested that is identifcation[:user][:login]
  - the date suggest is identification[:created_at][details][date]

I should probably forget about the date unless I can get it for both provisionals and non-provisionals.

Above might be a new class.
