### ISSUE TITLE
Clean up initial comment

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2387]
### Tasks
- [x] Subject of initial comment to something like "++Imported++ iNat Data ++Snapshot++ 2024-08-26 07:27:34 -0700"
- [x] Warn about what's not imported.
- [x] Change question marks to "none" or short description
- [x] Better Sequence and Observation field handling: value = "None" if there aren't any.
- [x] Clean up stray close bracket at end of comment.
