### ISSUE TITLE
Clean up for Basic iNat Import

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2397]
### TASKS
- [ ] #2387
- [ ] Delete unneeded success flash
- [ ] Delete JobTracker footer
- [ ] #2372 
- [ ] Fix CodeClimate offenses
- [ ] deep Rubocop (without inheriting from .rubocop_todo

**Comment by JoeCohen** [comment]
Copilot query for handling iNat request errors:

> Ruby on Rails. Job perform calls import_requested_observations, which calls next_page, which calls "RestClient::Request.execute(
      method: :get, url: "#{API_BASE}/observations?#{query}", headers: headers
    )". How can I deal with this error by returning from nex_page and saving the RestClient error message in perform?
