### ISSUE TITLE
Stimulate all parts of iNat tracker display

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2460]
Use Stimulus to update non-`Status` parts of InatImportJobTracker#show . (Stimulus already updates `Status`.)
Files:

> app/models/inat_import.rb
app/models/inat_import_job_tracker.rb
app/javascript/controllers/inat-import-job_controller.js
app/controllers/inat_imports_controller.rb
app/controllers/inat_imports/job_trackers_controller.rb (Turbo endpoint)
app/jobs/inat_import_job.rb
app/views/controllers/inat_imports/show.html.erb
app/views/controllers/inat_imports/job_trackers/_updates.erb

Examples:
> app/javascript/controllers/field-slip-job_controller.js
app/controllers/field_slip_job_trackers_controller.rb (Turbo endpoint)
app/views/controllers/projects/field_slips/new.html.erb
app/views/controllers/projects/field_slips/_tracker_row.erb

- [x] Wireframe for page
- [x] Request wireframe feedback. Both re how to do it with Stimulus, UX.
- [x] Implement changes.
  - [x] use just one ivar to define endpoint 
  - [x] # importable
  - [x] # imported
  - [x] started - Note: Import starts before ImportJob
  - [x] ended - can be attr of Job
  - [x] elapsed - can be method of Job
  - [x] use `div` instead of `span` as dashboard.
  - [x]  better "view results" button: Can it sort by created_at, be limited to those created_at > start_time?
  - [x]  errors
  - [x] clear `ended` when import starts.
  - [ ]  graphic
- [x] make InatImportsContreoller#inat_authorization_url into a constant
- [x] update documentation in app/controllers/inat_imports_controller.rb

**Comment by JoeCohen** [comment]
> [2015-01-15 Slack DM] [11:45](https://mushroomobserver.slack.com/archives/D011FQX2CLV/p1736970344694559)
> Andrew Nimmo
 re: inat import, i believe you can certainly handle what you want to do by simply putting that whole paragraph (from Status to Finished) in the same partial that gets the Turbo updates. The spans for the values that are updated can be data-targets if you need to check them in Stimulus for whatever reason, but they don’t need to be as far as I can tell. The main thing is you just need to send the refreshed values to that partial as locals, the way you normally would, in Ruby. (In other words: You don’t need to update the span elements separately. Just update the whole “import dashboard”. It’s still a cheap update and it will happen every second, anyway.)
re: How to make Stimulus/Turbo stop updating when the import status is Done: just check the status data attribute in Stimulus before you send a request, I believe you’re already doing that. Your partial is updating the data-inat-import-status with the correct value every second. (edited)
