### ISSUE TITLE
Fungarium specimen hotlink

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2471]
Automatic hotlink both the MO Fungarium Record and Observation to the official (remote) Fungarium's specimen record (for MO Fungarium records with an accession number). 
- The MO Fungarium Record should link to a search for the remote fungarium's record for that accession number.
- Ditto for the MO Observation page.

### TODO
- [x] Obtain list of Fungaria searchable by MyCoPortal
- [x] Add Herbarium#mycoportable? method.
- [x] Hotlink on appropriate MO Fungarium Record pages
- [x] Replace MCP_COLLECTIONS hash with Herbaria table `mycoportal-db` numeric field
  - [x] add new field
  - [x] update our code to get db from table
- [x] Hotlink on appropriate Observation pages 
- [x] Herbarium show:  display `mycoportal_db`
- [x] Herbarium form: display `mycoportal_db`, instructions for finding db number
- [x] Herbarium update/save
- [x] **Bug** MO Fungarium record page is missing a link to the record. Ex: http://localhost:3000/herbarium_records/44948
- [x] In Herbarium form, help, the link to mcp should open in a new tab. Can't do this because the link is created by a xlation string
- [x] Rubocop
- [ ] PR
- [ ] Respond to suggestions
- [ ] Merge, Deploy, Close issue and switch attention to immediate post-deploy tasks #2555

>[MO] Question From pinonbistro@msn.com
2 messages
webmaster@mushroomobserver.org <webmaster@mushroomobserver.org>	Sun, Oct 6, 2024 at 4:55 PM
Reply-To: pinonbistro@msn.com
To: webmaster@mushroomobserver.org
(from User #4674 Terri Clements/Donna Fulton(pinonbistro))
I use MO as my master list for AZ specimens, collected by myself and others, that are vouchered and sequenced.  MO allows me to add both fungarium and GenBank accession numbers to MO obs created by others.  This is great but while the GenBank link is a hot link to the record on GenBank the fungarium record is not linked by a hot link to the fungarium.  The MycoPortal link is a hot link to the fungarium record but for some reason only the MO obs owner can add the MycoPortal link. It would seem to make sense to allow others to add the MP link.
>
>Thanks,
>
>Terri
webmaster mushroomobserver.org <webmaster@mushroomobserver.org>	Sun, Oct 6, 2024 at 7:27 PM
To: pinonbistro@msn.com
Bcc: "webmaster mushroomobserver.org" <webmaster@mushroomobserver.org>
Terri:
Good point. Thanks for the suggestion! 
I agree that more people should be able to create a hot link to the fungarium.
I'll create a ticket for this. I won't be able to look at it further for at least a week.
(The Northeast Mycological Foray, which is happening next weekend, is using MO Field Slips and is recording foray collections in MO; the MO developers are focused on making that happen with minimum glitches.)
Best,
Joe

**Comment by JoeCohen** [comment]
MO virtual herbarium which are mcp searchable:
```ruby
Herbarium.where(code: mcp_keys).pluck(:code)
  Herbarium Pluck (2.9ms)  SELECT `herbaria`.`code` FROM `herbaria` WHERE `herbaria`.`code` IN ('PH', 'ACAD', 'CHSC', 'N/A', 'BMSC', 'BISH', 'BRIT', 'BDWR', 'BRU', 'HSC-F', 'CDA-Fungi', 'HAY', 'AAFC-DAOM', 'WSP', 'CHRB', 'CLEMS', 'HCOA', 'CUP', 'CBBG', 'DEWV', 'DBG-DBG', 'DUKE', 'EIU', 'EWU', 'QCAM', 'TAM', 'BAFC-H', 'F', 'FNL', 'FLD', 'GLM', 'M', 'KR', 'FH', 'FR', 'IND', 'TAAM', 'EAA', 'INEP-F', 'PACA', 'USU-UTC', 'ICMP', 'ISC', 'SUCO', 'LSUM-Fungi', 'MUHW', 'BR', 'MU', 'MSC', 'MOR', 'CORD', 'CR', 'PC', 'MNA', 'IBUNAM-MEXU:FU', 'TNS-F', 'NMC-FUNGI', 'UT-M', 'L', 'NBM', 'NY', 'NYS', 'PDD', 'NCSLG', 'OSC', 'OSC-Lichens', 'USFWS-PRR', 'PUR', 'PUL', 'QFB', 'E', 'TRTC', 'TAES', 'SFSU', 'SBBG', 'LJF', 'CORT', 'SYRF', 'SWAT', 'S', 'TALL', 'IBUG', 'CMMF', 'UACCC', 'ARIZ', 'UARK', 'UBC', 'UC', 'UCSC', 'IRVC', 'LA', 'FTU', 'CSU', 'CINC', 'C', 'FLAS', 'GAM', 'GB', 'HAW-F', 'ILL', 'ILLS', 'KANU-KU-F', 'MAINE', 'WIN', 'MICH', 'MIN', 'MISS', 'MONTU', 'NEB', 'UNM-Fungi', 'UNCA-UNCA', 'NCU-Fungi', 'O', 'URV', 'USAM', 'USCH-Fungi', 'USF', 'TU', 'TENN-F', 'UCHT-F', 'TEX', 'VT', 'WTU', 'UWAL', 'WIS', 'UWSP', 'RMS', 'UPS-BOT', 'USAC-USCG Hongos', 'CFMR', 'FPF', 'BPI', 'VSC', 'VPI', 'YSU-F')
```

**Comment by JoeCohen** [comment]
How to get the MCP db number for a fungarium:
- https://www.mycoportal.org/portal/collections/index.php
- click the `more information` link to the right of the desired fungarium
- In the browser address bar for the resulting page, the db number is the integer to the right of `collid=`.
Example:  
<img width="621" alt="Screenshot 2024-11-30 at 10 02 50 AM" src="https://github.com/user-attachments/assets/6d3aba8c-ec83-47d4-a346-18676bbd319d">
