### ISSUE TITLE
Observation with geoloc should use smallest containing Location instead of Earth

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2501]
If an Observation has a geoloc then Observation.location should be the Location with minimum bounding rectangle which contains obs.lat and obs.lng, instead of Earth.
> Nathan Wilson Sun, Nov 3, 9:06 AM (23 hours ago)
Sounds great!
>> On Sun, Nov 3, 2024 at 11:10 Joseph Cohen <jdcohenesq@gmail.com> wrote:
... I also don't like all the Obss have geoloc, but have lat/ng. These mostly (all? 99%) are coming from the API. 
Simple solution?:
>> - Observation before_save callback (pseudo-code)
>> - where = minimal_bounding_rectangle(lat, lgn)  where == Earth && lat.present?; 
Possibly limit this to Observations being created via the API. ...

### Tasks
- [x] API Test of posting Obs with lat/lng & Earth
- [x] Check case of lat/lng not contained in Earth (currently 89, -89, 179, -179)
- [ ] Resolve Earth fixture vs db discrepancy
- [x] Possibly deal with weirdly incorrectly defined Locations.

**Comment by JoeCohen** [comment]
API doesn't use `Observation.save`, so callback approach does not work for API-created Observations.

**Comment by JoeCohen** [comment]
webserver currently requires -89 <= lat <= 89, -179 <= lng <= 179
But if lat is between +/-89 and the closest pole, or lng is between +/- 179 and 180, webserver gives a flash error:
>Latitude and longitude must be real numbers between -90 and 90, and -180 and 180 respectively. Use decimal notation or degrees/minutes/seconds. Examples:
-123.4567
...

There are parts of Siberia, Fiji, other Pacific islands (and Arctic, Antarctic) which are not contained by those boundaries.
