### ISSUE TITLE
iNatImport hung on Authenticating

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2505]
iNatImport intermittently hangs in the state "Authenticating". This has been reported by multiple users. See, e.g.,
- [Slack General 2014-11-09 09:51 post from @AlanRockefeller](https://mushroomobserver.slack.com/archives/C040TH9FV/p1731174693112809)
- [email to webmaster Nov 15, 2024, 10:37 AM](https://mail.google.com/mail/u/0/?pli=1#search/inat+import/QgrcJHsTnPhQcxHPcssnDVMkFVdGQLxLgXG)
- other emails to webmaster.

### Tasks
- [x] Import until error replicated. 
Done. See [Comment Below, "Finally reproduced this once."](https://github.com/MushroomObserver/mushroom-observer/issues/2505#issuecomment-2480628742)
- [x] Review Rails Docs [Active Jobs Basics](https://guides.rubyonrails.org/active_job_basics.html)
- [x] Review Rails docs [Action Cable Overview](https://guides.rubyonrails.org/action_cable_overview.html)
Irrelevant
- [x] Review [Solid Queue documentation](https://github.com/rails/solid_queue?tab=readme-ov-file#solid-queue)
- [x] Review [mission_control-jobs documentation](https://github.com/rails/mission_control-jobs)
- [x] explicitly log `InatImportController#authorization_response` call to `perform_later`.
- [x] log start of InatImportJob in first line (instead of 2nd)
- [x] include param in above
- [x] job log entries in UTC
- [x] remove logging in InatImport object
- [x] remove InatImport.log column
- [x] Add [mission_control-jobs gem](https://github.com/rails/mission_control-jobs)
- [x] Add admin UI for `mission_control-jobs`

**Comment by JoeCohen** [comment]
Finally reproduced this once.  

### Import from iNat form:
>Your iNat Username (mandatory):
jdcohenesq
Comma separated list of up to 10 observation #s:
**251839766**

### iNatImportsController.rb relevant lines
```ruby
    def create
      ...
      @inat_import = InatImport.find_or_create_by(user: User.current)
      @inat_import.update(state: "Authorizing",
                          import_all: params[:all],
                          importables: 0, imported_count: 0,
                          inat_ids: params[:inat_ids],
                          inat_username: params[:inat_username].strip,
                          response_errors: "", token: "", log: [])

      request_inat_user_authorization
    end
    ...

    def request_inat_user_authorization
      redirect_to(inat_authorization_url, allow_other_host: true)
    end

    def authorization_response
      auth_code = params[:code]
      return not_authorized if auth_code.blank?

      @inat_import = InatImport.find_or_create_by(user: User.current)
      @inat_import.update(token: auth_code, state: "Authenticating")
      tracker = InatImportJobTracker.create(inat_import: @inat_import.id)

      # InatImportJob.perform_now(@inat_import) # for manual testing
      InatImportJob.perform_later(@inat_import)

      redirect_to(inat_import_job_tracker_path(tracker.id))
    end
```

### iNatJob.rb relevant lines
```ruby
 queue_as :default

  def perform(inat_import)
    @inat_import = inat_import
    log("InatImportJob #{@inat_import.id} started, " \
        "user #{@inat_import.user_id}")
```

### Production Log (with comments):
iNatImportController kicks things off, redirects to iNat for authorization
```ruby
I, [2024-11-16T03:05:57.085685 #1930905]  INFO -- : Started POST "/observations/inat_imports" for 204.195.31.134
W, [2024-11-16T03:05:57.092088 #1930905]  WARN -- : user=4468 robot=N ip=204.195.31.134
W, [2024-11-16T03:05:59.358382 #1930905]  WARN -- : TIME: 2.27097318 302 observations/inat_imports create user 204.195.31.134	https://mushroomobserver.org/observations/inat_imports
```

 iNat calls the MO redirect_url (`authorization_response`) with a code param
```ruby
I, [2024-11-16T03:06:00.041668 #1930901]  INFO -- : Started GET "/observations/inat_imports/authorization_response?code=rTZwfpSSAI_FrkXlMxfc4LXS4eQEyA7PgfW5lDU78iM" for 204.195.31.134
W, [2024-11-16T03:06:00.049908 #1930901]  WARN -- : user=4468 robot=N ip=204.195.31.134
W, [2024-11-16T03:06:00.185951 #1930901]  WARN -- : TIME: 0.141724913 302 observations/inat_imports authorization_response user 204.195.31.134	https://mushroomobserver.org/observations/inat_imports/authorization_response?code=rTZwfpSSAI_FrkXlMxfc4LXS4eQEyA7PgfW5lDU78iM
```

iNatImportController creates (or redirects to?, or I  refresh)
```ruby
I, [2024-11-16T03:06:01.043386 #1930901]  INFO -- : Started GET "/inat_import_job_trackers/332" for 204.195.31.134
W, [2024-11-16T03:06:01.051281 #1930901]  WARN -- : user=4468 robot=N ip=204.195.31.134
W, [2024-11-16T03:06:01.253933 #1930901]  WARN -- : TIME: 0.208336236 200 inat_import_job_trackers show user 204.195.31.134	https://mushroomobserver.org/inat_import_job_trackers/332
```

What is this?
```ruby
I, [2024-11-16T03:06:01.476088 #1930901]  INFO -- : Finished "/cable" [WebSocket] for 204.195.31.134
```

I repeatedly click `Update Results` on the tracker page
```ruby
I, [2024-11-16T03:06:07.680419 #1930907]  INFO -- : Started GET "/inat_import_job_trackers/332" for 204.195.31.134
W, [2024-11-16T03:06:07.688078 #1930907]  WARN -- : user=4468 robot=N ip=204.195.31.134
W, [2024-11-16T03:06:07.830947 #1930907]  WARN -- : TIME: 0.148466271 200 inat_import_job_trackers show user 204.195.31.134	https://mushroomobserver.org/inat_import_job_trackers/332
I, [2024-11-16T03:06:18.312283 #1930907]  INFO -- : Started GET "/inat_import_job_trackers/332" for 204.195.31.134
W, [2024-11-16T03:06:18.318410 #1930907]  WARN -- : user=4468 robot=N ip=204.195.31.134
W, [2024-11-16T03:06:18.443448 #1930907]  WARN -- : TIME: 0.12951742 200 inat_import_job_trackers show user 204.195.31.134	https://mushroomobserver.org/inat_import_job_trackers/332
```

### Job Log last job
:  All of this precedes the events in the production log; 
2024-11-15 18:54:03 -0800 == 2024-11-16 02:54:03
So there’s nothing in the job.log for the hung event. 
```ruby
2024-11-15 18:53:53 -0800: InatImportJob 1 InatImportJob 1 started, user 4468
2024-11-15 18:53:53 -0800: InatImportJob 1 Getting SuperImporters
2024-11-15 18:53:54 -0800: InatImportJob 1 Got SuperImporters: ["MO Webmaster", "nathan", "D.TempestThomas", "Joe Cohen"]
2024-11-15 18:53:54 -0800: InatImportJob 1 Obtaining OAuth access token
2024-11-15 18:53:54 -0800: InatImportJob 1 Obtained OAuth access token: Mue*************************************FXM
2024-11-15 18:53:54 -0800: InatImportJob 1 Obtaining jwt
2024-11-15 18:53:54 -0800: InatImportJob 1 Obtained JWT API token: eyJ*****************************************************************************************************************************************************************************************xsg
2024-11-15 18:53:54 -0800: InatImportJob 1 Skipping own-obs check (SuperImporter)
2024-11-15 18:54:03 -0800: InatImportJob 1 Imported requested observations
2024-11-15 18:54:03 -0800: InatImportJob 1 Updating inat_import state to Done
2024-11-15 18:54:03 -0800: InatImportJob 1 Updated user inat_username
```

### InatImport objecct for the hung import.

Note: `inat_id` is the id requested in the form; token == `code` param received by `authorization_response`.
Thus InatImportsController#authorization_response`: received the code which was requested from iNat, updated the iNatImport object with the code and a new state: Authenticating.  

```ruby
irb(main):001> import = InatImport.find_by user_id: 4468
=> 
#<InatImport:0x00007f2870395c48
...
irb(main):002> import
=> 
#<InatImport:0x00007f2870395c48
 id: 1,
 user_id: 4468,
 state: "Authenticating",
 inat_ids: "251839766",
 created_at: Sun, 22 Sep 2024 22:23:00.935269000 EDT -04:00,
 updated_at: Fri, 15 Nov 2024 22:06:00.153008000 EST -05:00,
 token: "[FILTERED]",
 inat_username: "jdcohenesq",
 import_all: nil,
 importables: 0,
 imported_count: 0,
 response_errors: "",
 log: []>
irb(main):003> import.token
=> "rTZwfpSSAI_FrkXlMxfc4LXS4eQEyA7PgfW5lDU78iM"
```

**Comment by JoeCohen** [comment]
jdc notes from [Active Jobs Basics](https://guides.rubyonrails.org/active_job_basics.html):

>Rails by default comes with an asynchronous queuing implementation that runs jobs with an in-process thread pool. Jobs will run asynchronously, but **any jobs in the queue will be dropped upon restart**.

> Rails itself only provides an in-process queuing system, which only keeps the jobs in RAM. If the process crashes or the machine is reset, then all outstanding jobs are lost with the default async backend. This may be fine for smaller apps or non-critical jobs, but most production apps will need to pick a persistent backend.

Is it possible that this why some of our emails are not getting sent?
>Using the asynchronous queue from a Rake task (for example, to send an email using .deliver_later) will generally not work because Rake will likely end, causing the in-process thread pool to be deleted, before any/all of the .deliver_later emails are processed. To avoid this problem, use .deliver_now or run a persistent queue in development.

Am I doing the wrong thing with exceptions?
>Exceptions raised during the execution of the job can be handled with [rescue_from](https://api.rubyonrails.org/v8.0.0/classes/ActiveSupport/Rescuable/ClassMethods.html#method-i-rescue_from)
...
If an exception from a job is not rescued, then the job is referred to as "failed".

>A failed job will not be retried, unless configured otherwise.
It's possible to retry or discard a failed job by using [retry_on](https://api.rubyonrails.org/v8.0.0/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) or [discard_on](https://api.rubyonrails.org/v8.0.0/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-discard_on), respectively.

**Comment by JoeCohen** [comment]
jdc notes from [Solid Queue documentation](https://github.com/rails/solid_queue?tab=readme-ov-file#solid-queue)

>We have several types of actors in Solid Queue:
>
> - _Workers_ are in charge of picking jobs ready to run from queues and processing them. They work off the solid_queue_ready_executions table.
> - _Dispatchers_ are in charge of selecting jobs scheduled to run in the future that are due and dispatching them, which is simply moving them from the solid_queue_scheduled_executions table over to the solid_queue_ready_executions table so that workers can pick them up. On top of that, they do some maintenance work related to [concurrency controls](https://github.com/rails/solid_queue?tab=readme-ov-file#concurrency-controls).
> - The _scheduler_ manages [recurring tasks](https://github.com/rails/solid_queue?tab=readme-ov-file#recurring-tasks), enqueuing jobs for them when they're due.
> - The _supervisor_ runs workers and dispatchers according to the configuration, controls their heartbeats, and stops and starts them when needed.
