### ISSUE TITLE
MCP link post-deploy

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2555]
Legacy issue to be closed after creating issues for each Task

Follow-up after deploying #2552 

### Tasks

- [x] Populate some `mycoportal_db` fields
- [x] Contact relevant power users.
- [x] Limit MCP links to macrofungi. 
Something like kingdom fungi, not an asco lichen. Can I further limit this to macrofungi phyla?
- [x] Move MCP_COLLECTIONS to the db. See https://github.com/MushroomObserver/mushroom-observer/pull/2552#pullrequestreview-2471523557- [ ] Article, including telling herbarium curators how to fill that field.
- [x] How to deal with potential differences between IH Herbarium and MCP dataset. Can MCP have multiple datasets per IH Herbarium? Can I construct an MCP URL which searches selected multiple datasets?
- [x] Stop persisting default Fungarium?
- [x] Deal with phony Accession Numbers (for another PR)
  - [x] email @mo-nathan, @pellaea 
- [x] Receive some MCP details from Scott Bates

**Comment by JoeCohen** [comment]
MCP listed phyla:

- Ascomycota
- Basidiomycota
- Blastocldiomycota
- Chrytridiomycota
- Deuteromycota
- Fungi Incertaie Sedis
- Microsporidiomycota
- Neocallimastigomycota
- Zygomycota

Therefore shouldn't create links for obs 
whose name classification include Fungi, && phyluim.present? && !phylum.member?([the above list])
