### ISSUE TITLE
Remove MyCoPortal external links

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2569]
Because links to MCP are created automatically, we don't need this and should remove it from Show Observation.

### TASKS
- [x] Turf all the `hide_specimen_stuff?` code. (It prevents `FungariumRecord +` for Adolf's Obss.) 
- [ ] Make sure all _working_ MCP external links have a _working_ counterpart link in the Fungarium Record.
- [ ] Delete the MCP external link code.

**Comment by JoeCohen** [comment]
Is it even possible to make sure that the external links have a correct counterpart Fungarium Record? (Thank you, Adolf.)
