### ISSUE TITLE
Revise mcp_searchable 

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2571]
Revise `Herbarium#mcp_searchable?` to rely on a csv file (below) supplied by MyCoPortal rather than on the inline `MCP_COLLECTIONS` hash which I created.

### Tasks
- [x] Find a place for the file.
- [x] Get MCP db id from the file instead of a Herbarium column.
- [x] Revise `mcp_searchable?` logic
- [x] Revise link url logic
- [x] Remove `MCP_COLLECTIONS`
- [x] Review herbarium show
- [x] Review herbarium form
- [x] Review show observation
- [x] Review FungariumRecord show
- [x] Review FungariumRecord form
- [x] adjust mcp-collid logic to account for official abbrv != `coll acryonym`
Exs: TENN-F, NMC-FUNGI, UBC-Obs
- [x] Remove the Herbarium#mycoportal_db column
- [x] Manual test 
  - [x] existing links work
  - [x] new links
- [x] Rubocop
- [x] PR #2572
- [ ] Respond to PR comments

[mycoportal-collections.csv](https://github.com/user-attachments/files/18053821/mycoportal-collections.csv)
